spring.datasource.url: jdbc:h2:file:./fluxnova-h2-database
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: sa

fluxnova:
  bpm:
    test-user-setup:
      enabled: false
    generic-properties:
      properties:
        historyTimeToLive: P1D
    authorization:
      enabled: false
fluxnova.bpm.admin-user:
  id: demo
  password: demo