fluxnova:
  user:
    id: "fluxnova"
    firstName: "DefaultUser"
    lastName: "Example"
    email: "default@example.com"
    password: "Finos@1021"
  groups:
    - id: "fluxnovabpmusers"
      name: "Fluxnoav BPM Users"
      type: "SYSTEM"
  authorization:
    - type: 1
      resourceId: "*"

