spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: sa

fluxnova.bpm.admin-user:
  id: demo
  password: demo